[package]
org= "ballerinax"
name= "microsoft.onedrive"
version= "1.0.2"
authors = ["Ballerina"]
keywords = ["microsoft", "onedrive", "storage"]
repository = "https://github.com/ballerina-platform/module-ballerinax-microsoft.onedrive"
license = ["Apache-2.0"]

[build-options]
observability-included=true
