name: Deployment

on:
    release:
        types: [published]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action@slbeta6
              with:
                  args: pack ./onedrive
            - name: Ballerina Test
              uses: ballerina-platform/ballerina-action@slbeta6
              with:
                  args: test ./onedrive
              env:
                  REFRESH_URL: ${{ secrets.REFRESH_URL }}
                  REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
                  CLIENT_ID: ${{ secrets.CLIENT_ID }}
                  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
            - name: Ballerina Push
              uses: ballerina-platform/ballerina-action@slbeta6
              with:
                  args: push
              env:
                  WORKING_DIR: ./onedrive
                  BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_ACCESS_TOKEN }}
